module.exports = [
  'large dogs',
  'big dogs',
  'labs',
  'labradors',
  'labrador retrievers',
  'german shepherds',
  'german shepherd dogs',
  'poodles',
  'rottweilers',
  'boxers',
  'dobermans',
  'doberman pinschers',
  'australian shepherds',
  'vizslas',
  'weimaraners',
  'collies',
  'rough collies',
  'smooth collies',
  'rhodesian ridgebacks',
  'chesapeake bay retrievers',
  'belgian malinois',
  'shiba inus',
  'akitas',
  'soft coated wheaten terriers',
  'wheaten terriers',
  'portuguese water dogs',
  'airedale terriers',
  'dogues de bordeauxes',
  'old english sheepdogs',
  'english sheepdogs',
  'chow chows',
  'pitbulls',
  'american pitbulls',
  'amercian pitbull terriers',
  'bouvier des flandres',
  'nova scotia duck tolling retrievers',
  'standard schnauzers',
  'afghan hounds',
  'belgian tervurens',
  'gordon setters',
];
