module.exports = [
  'large dog',
  'big dog',
  'lab',
  'labrador',
  'labrador retriever',
  'german shepherd',
  'german shepherd dog',
  'poodle',
  'rottweiler',
  'boxer',
  'doberman',
  'doberman pinscher',
  'australian shepherd',
  'vizsla',
  'weimaraner',
  'collie',
  'rough collie',
  'smooth collie',
  'rhodesian ridgeback',
  'chesapeake bay retriever',
  'belgian malinois',
  'shiba inu',
  'akita',
  'soft coated wheaten terrier',
  'wheaten terrier',
  'portuguese water dog',
  'airedale terrier',
  'dogues de bordeaux',
  'old english sheepdog',
  'english sheepdog',
  'chow chow',
  'pitbull',
  'american pitbull',
  'amercian pitbull terrier',
  'bouvier des flandres',
  'nova scotia duck tolling retriever',
  'standard schnauzer',
  'afghan hound',
  'belgian tervuren',
  'gordon setter',
];
