module.exports = [
  'medium dogs',
  'golden retrievers',
  'siberian huskies',
  'german shorthaired pointers',
  'brittanys',
  'brittany spaniels',
  'springer spaniels',
  'english springer spaniels',
  'cocker spaniels',
  'english cocker spaniels',
  'american cocker spaniels',
  'border collies',
  'bloodhounds',
  'australian cattle dogs',
  'cattle dogs',
  'huskies',
  'samoyeds',
  'bull terriers',
  'whippets',
  'pointers',
  'german pointers',
  'german wirehaired pointers',
  'dalmatians',
  'chinese shar peis',
  'shar peis',
  'wirehaired pointing griffons',
  'setters',
  'irish setters',
  'staffordshire bull terriers',
  'staffies',
  'american staffordshire terriers',
  'basenjis',
  'boykin spaniels',
];
