module.exports = [
  'medium dog',
  'golden retriever',
  'siberian husky',
  'german shorthaired pointer',
  'brittany',
  'brittany spaniel',
  'springer spaniel',
  'english springer spaniel',
  'cocker spaniel',
  'english cocker spaniel',
  'american cocker spaniel',
  'border collie',
  'bloodhound',
  'australian cattle dog',
  'cattle dog',
  'husky',
  'samoyed',
  'bull terrier',
  'whippet',
  'pointer',
  'german pointer',
  'german wirehaired pointer',
  'dalmatian',
  'chinese shar pei',
  'shar pei',
  'wirehaired pointing griffon',
  'setter',
  'irish setter',
  'staffordshire bull terrier',
  'staffie',
  'american staffordshire terrier',
  'basenji',
  'boykin spaniel',
];
