module.exports = [
  'small dog',
  'little dog',
  'frenchie',
  'french bulldog',
  'bulldog',
  'dachshund',
  'corgi',
  'welsh corgi',
  'pembroke welsh corgi',
  'cardigan welsh corgi',
  'miniature schnauzer',
  'cavalier king charles spaniel',
  'shih tzu',
  'boston terrier',
  'havanese',
  'shetland sheepdog',
  'sheltie',
  'pug',
  'basset hound',
  'west highland white terrier',
  'westie',
  'bichon',
  'bichon frise',
  'scottish terrier',
  'cairn terrier',
  'lhasa apso',
  'russell terrier',
  'jack russell',
  'jack russell terrier',
  'chinese crested',
  'chinese crested dog',
  'keeshond',
  'border terrier',
  'brussels griffon',
  'tibetan terrier',
  'norwich terrier',
  'silky terrier',
  'miniature bull terrier',
  'irish terrier',
  'american eskimo dog',
  'parson russell terrier',
  'tibetan spaniel',
  'pekingese',
  'japanese spitz',
];
