module.exports = [
  'small dogs',
  'little dogs',
  'frenchies',
  'french bulldogs',
  'bulldogs',
  'dachshunds',
  'corgis',
  'welsh corgis',
  'pembroke welsh corgis',
  'cardigan welsh corgis',
  'miniature schnauzers',
  'cavalier king charles spaniels',
  'shih tzus',
  'boston terriers',
  'havanese',
  'shetland sheepdogs',
  'shelties',
  'pugs',
  'basset hounds',
  'west highland white terriers',
  'westies',
  'bichons',
  'bichon frises',
  'scottish terriers',
  'cairn terriers',
  'lhasa apsos',
  'russell terriers',
  'jack russells',
  'jack russell terriers',
  'chinese cresteds',
  'chinese crested dogs',
  'keeshonds',
  'border terriers',
  'brussels griffons',
  'tibetan terriers',
  'norwich terriers',
  'silky terriers',
  'miniature bull terriers',
  'irish terriers',
  'american eskimo dogs',
  'parson russell terriers',
  'tibetan spaniels',
  'pekingese',
  'japanese spitzes',
];
